# Configuration file for BobCat institutions.
NYU:
  getit_url: https://qa.getit.library.nyu.edu/nyu/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    breadcrumbs:
      title: NYU Libraries
      url: http://dev.library.nyu.edu
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYU&tab=reserves'

NYUSH:
  getit_url: https://qa.getit.library.nyu.edu/nyush/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/nyush
      remote:
        url: http://guides.nyu.edu/arch
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUSH&tab=nyushcr'

NYUAD:
  getit_url: https://qa.getit.library.nyu.edu/nyuad/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/nyuad
      remote:
        url: http://guides.nyu.edu/adarch
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYUAD&tab=nyuadcr'

CU:
  getit_url: https://qa.getit.library.nyu.edu/cu/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/cooper
      cu:
        url: "http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cu"
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=CU&tab=cucr'


NS:
  getit_url: https://qa.getit.library.nyu.edu/ns/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu/newschool
      remote:
        url: https://qa.arch.library.nyu.edu/ns
      databases:
        url: https://qa.arch.library.nyu.edu/ns/databases/alphabetical/

HSL:
  getit_url: https://qa.getit.library.nyu.edu/hsl/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account

NYSID:
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      nysid:
        url: http://bobcatdev.library.nyu.edu/nysid
      all:
        url: http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYSID&tab=all
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo_library/libweb/action/search.do?mode=Basic&vid=NYSID&tab=reserves'
