# Configuration file for BobCat institutions.
NYU:
  getit_url: https://qa.getit.library.nyu.edu/nyu/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    breadcrumbs:
      title: NYU Libraries
      url: http://dev.library.nyu.edu
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: http://bobcatdev.library.nyu.edu
      reserves:
        url: 'https://ares.library.nyu.edu'

NYUSH:
  getit_url: https://qa.getit.library.nyu.edu/nyush/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?vid=NYUSH'
      remote:
        url: http://guides.nyu.edu/arch
      reserves:
        url: 'https://ares.library.nyu.edu'

NYUAD:
  getit_url: https://qa.getit.library.nyu.edu/nyuad/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?vid=NYUAD'
      remote:
        url: https://guides.nyu.edu/adarch
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?tab=nyuadcr&search_scope=nyuadcr&vid=NYUAD'

CU:
  getit_url: https://qa.getit.library.nyu.edu/cu/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    tabs:
      all:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?vid=CU'
      cu:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?vid=CU&tab=cu'
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?tab=cucr&vid=CU'


NS:
  getit_url: https://qa.getit.library.nyu.edu/ns/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      all:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?vid=NS2-NUI'
      remote:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/jsearch?vid=NS2-NUI'
      databases:
        url: http://guides.library.newschool.edu/az.php
      journals:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/npsearch?vid=NS2-NUI'
      browse:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/browse?vid=NS2-NUI'

HSL:
  getit_url: https://qa.getit.library.nyu.edu/hsl/resolve?
  bobcat_url: http://bobcatdev.library.nyu.edu
  eshelf_url: https://qa.eshelf.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account

NYSID:
  eshelf_url: https://qa.eshelf.library.nyu.edu
  bobcat_url: http://bobcatdev.library.nyu.edu
  my_account_url: https://qa.eshelf.library.nyu.edu/account
  views:
    ill:
      url: https://dev.ill.library.nyu.edu
    tabs:
      nysid:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?tab=nysid&vid=NYSID'
      all:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?vid=NYSID&tab=all'
      reserves:
        url: 'http://bobcatdev.library.nyu.edu/primo-explore/search?tab=reserves&search_scope=reserves&vid=NYSID'
