# Configuration file for BobCat institutions.
NYU:
  default: true
  name: NYU Libraries
  auth:
    code: NYU
  getit_url: https://getit.library.nyu.edu/nyu/resolve?
  bobcat_url: http://bobcat.library.nyu.edu
  eshelf_url: https://eshelf.library.nyu.edu
  my_account_url: https://eshelf.library.nyu.edu/account
  bobcat_alias: nyu
  views:
    css: application
    dir: nyu
    breadcrumbs:
      title: NYU Libraries
      url: http://library.nyu.edu
    ill:
      link_html: My interlibrary loan (ILL)
      url: https://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: http://bobcat.library.nyu.edu
        tip: "Search NYU's catalog for books, journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings"
      remote:
        display: 'Articles & Databases'
        url: http://guides.nyu.edu/arch
        tip: Search databases for articles or browse databases by subject
      journals:
        display: Journals
        tip: Search for journals by title or for articles by citation
      reserves:
        display: Course Reserves
        url: 'https://ares.library.nyu.edu'
        tip: Search for library materials that are held at one location for a particular course
    login:
      name: NYU
      primary: nyu_shibboleth
      secondary:
        - bobst
        - nysid
        - cu
        - ns
      general_public: true

NYUSH:
  name: NYU Shanghai Library
  getit_url: https://getit.library.nyu.edu/nyush/resolve?
  link_to_parent: NYU
  bobcat_alias: nyush
  views:
    css: application_nyush
    dir: nyush
    breadcrumbs:
      title: NYU Shanghai Library
      url: https://shanghai.nyu.edu/academics/library
    ill:
      link_html: My interlibrary loan (ILL)
      url: https://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?vid=NYUSH'
        tip: "Search NYU's catalog for books, journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings"
      remote:
        display: 'Articles & Databases'
        url: http://guides.nyu.edu/arch
        tip: Search databases for articles or browse databases by subject
      journals:
        display: Journals
        tip: Search for journals by title or for articles by citation
      reserves:
        display: Course Reserves
        url: 'https://ares.library.nyu.edu'
        tip: Search for library materials that are held at one location for a particular course
    login:
      name: NYU
      primary: nyu_shibboleth
      secondary:
        - bobst

NYUAD:
  name: NYU Abu Dhabi Library
  getit_url: https://getit.library.nyu.edu/nyuad/resolve?
  bobcat_alias: nyuad
  views:
    css: application_nyuad
    dir: nyuad
    breadcrumbs:
      title: NYU Abu Dhabi Library
      url: https://nyuad.nyu.edu/en/library.html
    ill:
      link_html: My interlibrary loan (ILL)
      url: https://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?vid=NYUAD'
        tip: "Search NYU's catalog for books, journals, scripts, scores, archival materials, NYU dissertations, videos, sound recordings"
      remote:
        display: 'Articles & Databases'
        url: http://guides.nyu.edu/adarch
        tip: Search databases for articles or browse databases by subject
      journals:
        display: Journals
        tip: Search for journals by title or for articles by citation
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?tab=nyuadcr&search_scope=nyuadcr&vid=NYUAD'
        tip: Search for library materials that are held at one location for a particular course
    login:
      name: NYU
      primary: nyu_shibboleth
      secondary:
        - bobst

CU:
  name: The Cooper Union Library
  getit_url: https://getit.library.nyu.edu/cu/resolve?
  bobcat_alias: cooper
  auth:
    code: CU
  views:
    css: application_cu
    dir: cu
    breadcrumbs:
      title: Cooper Union Library
      url: http://library.cooper.edu
    tabs:
      all:
        display: Consortium Catalog
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?vid=CU'
        tip: 'Books & e-books, journals & e-journals, scripts, scores, archival materials, videos, sound recordings, and other materials in the Consortium libraries'
      cu:
        display: Cooper Library Catalog
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?vid=CU&tab=cu'
        tip: 'Books & e-books, journals & e-journals, videos, and other materials in the Cooper Union Library'
      journals:
        display: E-Journals
        tip: Browse e-journals by title or search for a specific article
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?tab=cucr&vid=CU'
        tip: 'Search course reserves by instructor, course name or number, author, title, and other terms'
    login:
      name: Cooper Union
      primary: aleph
      secondary:
        - nyu
        - ns
        - nysid
      general_public: true


NS:
  name: New School Libraries
  getit_url: https://getit.library.nyu.edu/ns/resolve?
  bobcat_alias: newschool
  auth:
    code: NS
  views:
    css: application_ns
    dir: ns
    breadcrumbs:
      title: New School Libraries
      url: http://library.newschool.edu
    ill:
      link_html: My interlibrary loan (ILL)
      url: https://ill.library.nyu.edu
    tabs:
      all:
        display: 'Books & More'
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?vid=NS2-NUI'
        tip: Find resources in All Consortium Libraries
      remote:
        display: Journals
        url: 'http://bobcat.library.nyu.edu/primo-explore/jsearch?vid=NS2-NUI'
        tip: 'Search for articles, images and media by subject'
      databases:
        display: Databases
        url: http://guides.library.newschool.edu/az.php
        tip: All databases by title
      journals:
        display: Newspapers
        url: 'http://bobcat.library.nyu.edu/primo-explore/npsearch?vid=NS2-NUI'
        tip: Newspaper search
      browse:
        display: Browse
        url: 'http://bobcat.library.nyu.edu/primo-explore/browse?vid=NS2-NUI'
        tip: Browse
    login:
      name: The New School
      primary: new_school_ldap
      secondary:
        - nyu
        - cu
        - nysid
      general_public: true

HSL:
  name: NYU Health Sciences Library
  getit_url: https://getit.library.nyu.edu/hsl/resolve?
  auth:
    code: HSL
  views:
    css: application_hsl
    dir: hsl
    breadcrumbs:
      title: NYU Health Sciences Library
      url: http://hsl.med.nyu.edu/
    login:
      name: NYU
      primary: nyu_shibboleth
      secondary:
        - bobst
  services:
    Dummy:
      disabled: true

NYSID:
  name: New York School of Interior Design
  views:
    css: application_nysid
    dir: nysid
    breadcrumbs:
      title: New York School of Interior Design Library
      url: http://library.nysid.edu/library
    ill:
      link_html: My interlibrary loan (ILL)
      url: https://ill.library.nyu.edu
    tabs:
      nysid:
        display: NYSID Resources
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?tab=nysid&vid=NYSID'
        tip: Find New York School of Interior Design Resources
      all:
        display: 'Books & More'
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?vid=NYSID&tab=all'
        tip: 'Find Resources in All BobCat Libraries'
      reserves:
        display: Course Reserves
        url: 'http://bobcat.library.nyu.edu/primo-explore/search?tab=reserves&search_scope=reserves&vid=NYSID'
        tip: 'Search for books on reserve by instructor, course name or number, author, title, and other terms."'
    login:
      name: NYSID
      primary: aleph
      secondary:
        - nyu
        - ns
        - cu
      general_public: true
